### ISSUE TITLE
dont find the dataset OTI

### ISSUE THREAD

**Issue by MartyMestdagh** [DillonHammill/CytoGate#4]
Hi,
My name is Martin, a bioinformatician developper.
I'm working with openCyto package and see yours issues.
But i'm looking your package and i can't find the dataset OTI; I realize your instructions from readme:
 data(OTI, package = "CytoGate")
          Warning message:
In data(OTI, package = "CytoGate") : dataset ‘OTI’ not found
Did you change the name or something ?
Best regards!
Martin

**Comment by DillonHammill** [comment]
Hi Martin,

Yes I recently changed the name to "Activation" as in the vignette. I will update the name in the README & update documentation with additional experimental details.

https://github.com/DillonHammill/CytoGate/blob/master/vignettes/CytoGate.Rmd

Thanks for trying out the package, let me know if you encounter any problems!
Dillon
