### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by hrj21** [DillonHammill/CytoGate#8]
Hello! Thank you for creating this package. I'm trying to install it, but when I run: `devtools::install_github("DillonHammill/CytoGate")`, I get the error:

```
Downloading GitHub repo DillonHammill/CytoGate@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/DillonHammill/CytoGate/tarball/HEAD'
```

Am I doing something wrong?
Best wishes
Hefin

**Comment by DillonHammill** [comment]
@hrj21, CytoGate is no longer actively maintained. Please switch to using the far superior CytoExploreR package:
https://dillonhammill.github.io/CytoExploreR/

**Comment by hrj21** [comment]
Ah thank you (and for your quick response). I will check out CytoExploreR instead :)

**Comment by DillonHammill** [comment]
No problem at all. Let me know if you need any help. The Getting Started tab on the CytoExploreR website is a good place to start.
